name: Node.js CI
on: [push, pull_request]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '18.x'

            - name: Install dependencies
              run: npm install

            - name: Run User Service Tests
              run: npm test tests/users.test.js

            - name: Run Product Service Tests
              run: npm test tests/products.test.js

            - name: Run Order Service Tests
              run: npm test tests/orders.test.js

            - name: Generate Test Report
              run: |
                  echo "==================================="
                  echo "Test Report Summary"
                  echo "==================================="
                  npm test -- --verbose
